directory/urls.py
from django.urls import path
from directory import views

app_name = 'directory'

urlpatterns = [
    path('autocomplete/office', views.OfficeAutocomplete.as_view(), name='autocomplete_office'),
    path('autocomplete/employee', views.EmployeeAutocomplete.as_view(), name='autocomplete_employee'),
    path('autocomplete/district', views.DistrictAutocomplete.as_view(), name='autocomplete_district'),
    path('autocomplete/unit_measure', views.UnitMeasureAutocomplete.as_view(), name='autocomplete_unit_measure'),
    path('autocomplete/task', views.TaskAutocomplete.as_view(), name='autocomplete_task'),
    path('autocomplete/work', views.WorkAutocomplete.as_view(), name='autocomplete_work'),
    path('autocomplete/material', views.MaterialAutocomplete.as_view(), name='autocomplete_material'),

    path('office', views.office, name='office'),
    path('office/listing', views.office_listing, name='office_listing'),
    path('office/add', views.office_add, name='office_add'),
    path('office/<int:office_pk>/change', views.office_change, name='office_change'),
    path('office/<int:office_pk>/delete_complete', views.office_delete_complete, name='office_delete_complete'),

    path('employees', views.employees, name='employees'),
    path('employees/listing', views.employees_listing, name='employees_listing'),
    path('employees/add', views.employees_add, name='employees_add'),
    path('employees/<int:employee_pk>/change', views.employees_change, name='employees_change'),
    path('employees/<int:employee_pk>/change_password', views.employees_change_password, name='employees_change_password'),
    path('employees/<int:employee_pk>/delete_complete', views.employees_delete_complete, name='employees_delete_complete'),

    path('material', views.material, name='material'),
    path('material/listing', views.material_listing, name='material_listing'),
    path('material/add', views.material_add, name='material_add'),
    path('material/<int:material_pk>/change', views.material_change, name='material_change'),
    path('material/<int:material_pk>/delete_complete', views.material_delete_complete, name='material_delete_complete'),
    
    path('work', views.work, name='work'),
    path('work/listing', views.work_listing, name='work_listing'),
    path('work/add', views.work_add, name='work_add'),
    path('work/<int:work_pk>/change', views.work_change, name='work_change'),
    path('work/<int:work_pk>/delete_complete', views.work_delete_complete, name='work_delete_complete'),
    
]

home/urls.py
from django.urls import path
from home import views

app_name = 'home'

urlpatterns = [
	path('', views.home, name="home"),
    
]

directory/views/autocomplete.py
from django.db.models import Q, OuterRef, Exists

from dal import autocomplete
from dal_select2.views import Select2ViewMixin
from dal.views import BaseQuerySetView

from directory.models import District, Office, Employee, UnitMeasure, Task, Work, Material


class TaskAutocomplete(Select2ViewMixin, BaseQuerySetView):
    def get_queryset(self):
        if not self.request.user.is_authenticated:
            return Task.objects.none()
        qs = Task.objects.all()

        self_pk = self.forwarded.get('self')
        exclude_children = self.forwarded.get('exclude_children')
        if self_pk and exclude_children:
            current = Task.objects.get(pk=self_pk)
            qs = qs.exclude(pk__in=[o.pk for o in current.get_descendants(include_self=True)])

        if self.q:
            qs = qs.filter(task_name__icontains=self.q)

        return qs
    

    def get_results(self, context):
        return [
            {
                'id': self.get_result_value(result),
                'text': self.get_result_label(result),
                'selected_text': self.get_selected_result_label(result),
            } for result in context['object_list']
        ]
    
    def get_result_label(self, item):
        return str(item)

    def get_selected_result_label(self, item):
        return str(item)
    

class WorkAutocomplete(autocomplete.Select2QuerySetView):
    def get_queryset(self):
        if not self.request.user.is_authenticated:
            return Work.objects.none()
        qs = Work.objects.all()
        if self.q:
            qs = qs.filter(work_code__icontains=self.q, work_name__icontains=self.q)
        return qs
    
class MaterialAutocomplete(autocomplete.Select2QuerySetView):
    def get_queryset(self):
        if not self.request.user.is_authenticated:
            return Material.objects.none()
        qs = Material.objects.all()
        if self.q:
            qs = qs.filter(material_code__icontains=self.q, material_name__icontains=self.q)
        return qs


class DistrictAutocomplete(autocomplete.Select2QuerySetView):
    def get_queryset(self):
        if not self.request.user.is_authenticated:
            return District.objects.none()
        qs = District.objects.all()
        if self.q:
            qs = qs.filter(district_name__icontains=self.q)
        return qs
    

class UnitMeasureAutocomplete(autocomplete.Select2QuerySetView):
    def get_queryset(self):
        if not self.request.user.is_authenticated:
            return UnitMeasure.objects.none()
        qs = UnitMeasure.objects.all()
        if self.q:
            qs = qs.filter(unit_name__icontains=self.q)
        return qs
    

class OfficeAutocomplete(autocomplete.Select2QuerySetView):
    def get_queryset(self):
        if not self.request.user.is_authenticated:
            return Office.objects.none()
        
        qs = Office.objects.all()
        
        s_office_type = self.forwarded.get('s_office_type')
        if s_office_type:
            qs = qs.filter(s_office_type=s_office_type)

        if self.q:
            qs = qs.filter(office_name__icontains=self.q)
        return qs


class EmployeeAutocomplete(autocomplete.Select2QuerySetView):
    def get_queryset(self):
        if not self.request.user.is_authenticated:
            return Employee.objects.none()
        qs = Employee.objects.all()
        
        is_active = self.forwarded.get('is_active')
        if is_active:
            qs = qs.filter(is_active=bool(is_active))

        if self.q:
            qs = qs.filter(
                Q(employee_name__icontains=self.q)
                | Q(phone_number__icontains=self.q)
                | Q(user__username__icontains=self.q)
                )
        return qs

directory/views/employees.py
from django.http import JsonResponse
from django.shortcuts import render, get_object_or_404
from django.utils.translation import gettext_lazy as _
from django.core.paginator import Paginator
from django.contrib.auth.decorators import login_required

from common.utils import get_count_per_page
from common.decorators import deletion_error_capture
from directory.forms import EmployeeAddForm, EmployeeChangeForm, PasswordChangeForm
from directory.filters import EmployeeFilterForm
from directory.models import Employee


@login_required
def employees(request):
    """Каркас страницы"""
    return render(request, 'directory/employees/employees.html', {
        'ff': EmployeeFilterForm(request.GET),
        'page_title': _('Пользователи')
        })


@login_required
def employees_listing(request):
    """Ajax. Список"""
    ff = EmployeeFilterForm(request.GET)
    paginator = Paginator(ff.qs, get_count_per_page(request=request))
    return render(request, 'directory/employees/employees_listing.html', {
        'data': paginator.get_page(request.GET.get('page')),
        'ff': ff,
        'count': ff.qs.count()
        })


@login_required
def employees_add(request):
    """Ajax. Добавление"""
    if request.method == 'POST':
        form = EmployeeAddForm(request.POST, user=request.user)
        if form.is_valid():
            form.save()
            return employees_listing(request=request)
        return JsonResponse({ 'success': False, 'errors': form.errors })  
    return render(request, 'directory/employees/employees_add.html', { 'form': EmployeeAddForm(user=request.user) })


@login_required
def employees_change(request, employee_pk):
    """Ajax. Редактирование"""
    employee = get_object_or_404(Employee, pk=employee_pk)
    if request.method == 'POST':
        form = EmployeeChangeForm(request.POST, instance=employee)
        if form.is_valid():
            form.save()
            return employees_listing(request=request)
        return JsonResponse({ 'success': False, 'errors': form.errors })
    return render(request, 'directory/employees/employees_change.html', {
        'form': EmployeeChangeForm(instance=employee),
        'employee': employee
        })


@login_required
def employees_change_password(request, employee_pk):
    """Ajax. Смена пароля"""
    employee = get_object_or_404(Employee, pk=employee_pk)
    if request.method == 'POST':
        form = PasswordChangeForm(request.POST, user=employee.user)
        if form.is_valid():
            form.save()
            return employees_listing(request=request)
        return JsonResponse({ 'success': False, 'errors': form.errors })
    return render(request, 'directory/employees/employees_change_password.html', {
        'form': PasswordChangeForm(user=employee),
        'employee': employee
        })


@login_required
@deletion_error_capture
def employees_delete_complete(request, employee_pk):
    """Ajax. Удаление"""
    employee = get_object_or_404(Employee, pk=employee_pk)
    employee.delete()
    return employees_listing(request=request)

directory/views/material.py
from django.http import JsonResponse
from django.shortcuts import render, get_object_or_404
from django.utils.translation import gettext_lazy as _
from django.core.paginator import Paginator
from django.contrib.auth.decorators import login_required

from common.utils import get_count_per_page
from common.decorators import deletion_error_capture
from directory.forms import MaterialForm
from directory.filters import MaterialFilterForm
from directory.models import Material


@login_required
def material(request):
    """Каркас страницы"""
    return render(request, 'directory/material/material.html', {
        'ff': MaterialFilterForm(),
        'page_title': _('Материалы')
        })


@login_required
def material_listing(request):
    """Ajax. Список"""
    ff = MaterialFilterForm(request.GET)
    paginator = Paginator(ff.qs, get_count_per_page(request=request))
    return render(request, 'directory/material/material_listing.html', {
        'data': paginator.get_page(request.GET.get('page')),
        'ff': ff,
        'count': ff.qs.count()
        })


@login_required
def material_add(request):
    """Ajax. Добавление"""
    if request.method == 'POST':
        form = MaterialForm(request.POST)
        if form.is_valid():
            form.save()
            return material_listing(request=request)
        return JsonResponse({ 'success': False, 'errors': form.errors })
    return render(request, 'directory/material/material_add.html', { 'form': MaterialForm() })


@login_required
def material_change(request, material_pk):
    """Ajax. Редактирование"""
    m = get_object_or_404(Material, pk=material_pk)
    if request.method == 'POST':
        form = MaterialForm(request.POST, instance=m)
        if form.is_valid():
            form.save()
            return material_listing(request=request)
        return JsonResponse({ 'success': False, 'errors': form.errors })
    return render(request, 'directory/material/material_change.html', {
        'form': MaterialForm(instance=m),
        'm': m
        })


@login_required
@deletion_error_capture
def material_delete_complete(request, material_pk):
    """Ajax. Удаление"""
    m = get_object_or_404(Material, pk=material_pk)
    m.delete()
    return material_listing(request=request)

directory/views/office.py
from django.http import JsonResponse
from django.shortcuts import render, get_object_or_404
from django.utils.translation import gettext_lazy as _
from django.core.paginator import Paginator
from django.contrib.auth.decorators import login_required

from common.utils import get_count_per_page
from common.decorators import deletion_error_capture
from directory.forms import OfficeForm
from directory.filters import OfficeFilterForm
from directory.models import Office


@login_required
def office(request):
    """Каркас страницы"""
    return render(request, 'directory/office/office.html', {
        'ff': OfficeFilterForm(),
        'page_title': _('Организации')
        })


@login_required
def office_listing(request):
    """Ajax. Список"""
    ff = OfficeFilterForm(request.GET)
    paginator = Paginator(ff.qs, get_count_per_page(request=request))
    return render(request, 'directory/office/office_listing.html', {
        'data': paginator.get_page(request.GET.get('page')),
        'ff': ff,
        'count': ff.qs.count()
        })


@login_required
def office_add(request):
    """Ajax. Добавление"""
    if request.method == 'POST':
        form = OfficeForm(request.POST, user=request.user)
        if form.is_valid():
            form.save()
            return office_listing(request=request)
        return JsonResponse({ 'success': False, 'errors': form.errors })
    return render(request, 'directory/office/office_add.html', { 'form': OfficeForm(user=request.user) })


@login_required
def office_change(request, office_pk):
    """Ajax. Редактирование"""
    obj = get_object_or_404(Office, pk=office_pk)
    if request.method == 'POST':
        form = OfficeForm(request.POST, instance=obj, user=request.user)
        if form.is_valid():
            form.save()
            return office_listing(request=request)
        return JsonResponse({ 'success': False, 'errors': form.errors })
    return render(request, 'directory/office/office_change.html', {
        'form': OfficeForm(instance=obj, user=request.user),
        'obj': obj
        })


@login_required
@deletion_error_capture
def office_delete_complete(request, office_pk):
    """Ajax. Удаление"""
    obj = get_object_or_404(Office, pk=office_pk)
    obj.delete()
    return office_listing(request=request)

directory/views/work.py
from django.http import JsonResponse
from django.shortcuts import render, get_object_or_404
from django.utils.translation import gettext_lazy as _
from django.core.paginator import Paginator
from django.contrib.auth.decorators import login_required

from common.utils import get_count_per_page
from common.decorators import deletion_error_capture
from directory.forms import WorkForm
from directory.filters import WorkFilterForm
from directory.models import Work


@login_required
def work(request):
    """Каркас страницы"""
    return render(request, 'directory/work/work.html', {
        'ff': WorkFilterForm(),
        'page_title': _('Работы')
        })


@login_required
def work_listing(request):
    """Ajax. Список"""
    ff = WorkFilterForm(request.GET)
    paginator = Paginator(ff.qs, get_count_per_page(request=request))
    return render(request, 'directory/work/work_listing.html', {
        'data': paginator.get_page(request.GET.get('page')),
        'ff': ff,
        'count': ff.qs.count()
        })


@login_required
def work_add(request):
    """Ajax. Добавление"""
    if request.method == 'POST':
        form = WorkForm(request.POST)
        if form.is_valid():
            form.save()
            return work_listing(request=request)
        return JsonResponse({ 'success': False, 'errors': form.errors })
    return render(request, 'directory/work/work_add.html', { 'form': WorkForm() })


@login_required
def work_change(request, work_pk):
    """Ajax. Редактирование"""
    w = get_object_or_404(Work, pk=work_pk)
    if request.method == 'POST':
        form = WorkForm(request.POST, instance=w)
        if form.is_valid():
            form.save()
            return work_listing(request=request)
        return JsonResponse({ 'success': False, 'errors': form.errors })
    return render(request, 'directory/work/work_change.html', {
        'form': WorkForm(instance=w),
        'w': w
        })


@login_required
@deletion_error_capture
def work_delete_complete(request, work_pk):
    """Ajax. Удаление"""
    w = get_object_or_404(Work, pk=work_pk)
    w.delete()
    return work_listing(request=request)

directory/templates/directory/employees/employees.html
{% extends 'base.html' %}

{% block title %}{{ block.super }} - {{ page_title }}{% endblock %}

{% block breadcrumbs %}
{% url 'home' as home_url %}{% breadcrumb "Главная" home_url %}
{% breadcrumb 'Справочники' %}
{% breadcrumb page_title %}
{% endblock %}

{% block content %}
<fieldset class="mt-5 bg-white">
    <div class="p-4 pb-1 bg-secondary bg-opacity-10">
        <form id="ff" class="ajax_form" data-target="#datalist" action="{% url 'directory:employees_listing' %}" method="get">
            {% include "_parts/form.html" with form=ff %}
        </form>
    </div>
    <div id="datalist" class="ajax-container p-4 mt-2" data-form="#ff"></div> 
</fieldset>
{% endblock %}

directory/templates/directory/employees/employees_add.html
<form enctype="multipart/form-data" action="{% url 'directory:employees_add' %}?{% url_qs %}" method="post">
    {% include "_parts/form.html" with form=form %}
</form>

directory/templates/directory/employees/employees_change.html
<form enctype="multipart/form-data" action="{% url 'directory:employees_change' employee.pk %}?{% url_qs %}" method="post">
    {% include "_parts/form.html" with form=form %}
</form>

directory/templates/directory/employees/employees_change_password.html
<form enctype="multipart/form-data" action="{% url 'directory:employees_change_password' employee.pk %}?{% url_qs %}" method="post">
    {% include "_parts/form.html" with form=form %}
</form>

directory/templates/directory/employees/employees_listing.html
<table class="table table-hover table-fixed-head">
    <thead>
        <tr>
            <th scope="col" class="fit">#</th>
            <th scope="col" class="fit"></th>
            <th scope="col">Организация</th>
            <th scope="col">ФИО</th>
            <th scope="col">Логин</th>
            <th scope="col">Контакты</th>
            <th scope="col"></th>
            <th scope="col" class="text-end text-nowrap">
                {% if check_perm.directory.employees_add %}
                <a class="modal_link" title="Добавить"
                    data-modal-title="Новый пользователь" 
                    data-modal-size="modal-lg"
                    data-target="#datalist"
                    data-href="{% url 'directory:employees_add' %}?{% url_qs %}">{{ 'Добавить'|action_icon }}</a>
                {% endif %}
            </th>
        </tr>
    </thead>
    <tbody>
        {% for o in data %}
        <tr>
            <th scope="row">{{ o.pk }}</th>
            <td>{{ o.is_active|bool_icon }}</td>
            <td class="lh-sm">
                {{ o.s_office }}
            </td>
            <td class="lh-sm">
                {{ o.employee_name|highlight:ff.cleaned_data.q }}
            </td>
            <td class="lh-sm">
                {{ o.user.username|highlight:ff.cleaned_data.q }}
                <div class="text-muted small">{{ o.s_role }}</div>
            </td>
            <td class="lh-sm">
                {% if o.phone_number %}<div>{{ o.phone_number|highlight:ff.cleaned_data.q }}</div>{% endif %}
                {% if o.e_mail %}<div>{{ o.e_mail|highlight:ff.cleaned_data.q }}</div>{% endif %}
            </td>
            <td class="text-nowrap">
                {% if check_perm.directory.employees_change_password %}
                <a class="modal-link" 
                    data-modal-title='Смена пароля пользователя "{{ o.employee_name }}"' 
                    data-modal-size="modal-md"
                    data-target="#datalist"
                    data-href="{% url 'directory:employees_change_password' o.pk %}?{% url_qs %}">Сменить пароль</a>
                {% endif %}
            </td>
            <td class="text-nowrap text-end">
                {% if check_perm.directory.employees_change %}
                <a class="modal-link me-2" title="Изменить" 
                    data-modal-title='Изменение данных пользователя "{{ o.employee_name }}"' 
                    data-modal-size="modal-lg"
                    data-target="#datalist"
                    data-href="{% url 'directory:employees_change' o.pk %}?{% url_qs %}">{{ 'Изменить'|action_icon }}</a>
                {% endif %}
                {% if check_perm.directory.employees_delete_complete %}
                <a class="text-danger dialog-delete" title="Удалить" 
                    data-target="#datalist" 
                    data-href="{% url 'directory:employees_delete_complete' o.pk %}?{% url_qs %}">{{'Удалить'|action_icon }}</a>
                {% endif %}
            </td>
        </tr>
        {% endfor %}
    </tbody>
    <tfoot>
        <tr>
            <td colspan="100">
                <div class="form-text">Количество записей: {{ count }}</div>
            </td>
        </tr>
    </tfoot>
</table>

<div class="my-2">
    {% url 'directory:employees_listing' as pager_base_url %}
    {% include '_parts/pager_ajax.html' with objects=data target='#datalist' base_url=pager_base_url %}
</div>