home/urls.py
from django.urls import path
from home import views

app_name = 'home'

urlpatterns = [
	path('', views.home, name="home"),
    
]

tasks/urls.py
from django.urls import path

from tasks import views

app_name = 'tasks'

urlpatterns = [
    path('', views.home, name='home'),
    path('listing', views.listing, name='listing'),
    path('add', views.add, name='add'),
    path('<int:task_pk>/change', views.change, name='change'),
    path('<int:task_pk>/delete_complete', views.delete_complete, name='delete_complete'),
    
    path('<int:task_pk>/material/listing', views.task_material_listing, name='task_material_listing'),
    path('<int:task_pk>/material/add', views.task_material_add, name='task_material_add'),
    path('material/<int:task_material_pk>/change', views.task_material_change, name='task_material_change'),
    path('material/<int:task_material_pk>/delete_complete', views.task_material_delete_complete, name='task_material_delete_complete'),
    
]

tasks/forms.py
from django import forms
from django.utils.translation import gettext_lazy as _
from django.db.models import Q
from django.contrib.auth.forms import SetPasswordForm
from django.db import transaction

from crispy_forms.helper import FormHelper
from crispy_forms.layout import *
from crispy_forms.bootstrap import *

from dal import forward

from common.form.widgets import ModelSelect2ForwardExtras, ModelSelect2MultipleForwardExtras
from common.form.formsets import ModelFormSet
from common.form.fields import FormsetField, FormsetFormMixin
from directory.models import Task, TaskMaterial


def _helper():
    helper = FormHelper()
    helper.form_tag = False
    helper.include_media = False
    return helper


class TaskMaterialForm(forms.ModelForm):
    """Форма добавления/редактирования материала к задаче"""
    class Meta:
        model = TaskMaterial
        fields = [
            's_material',
            'material_count',
            'material_cost',
            'labor_cost',
            'work_cost',
            'material_count_fact',
            'material_cost_total',
            'work_cost_total',
            ]
        widgets = {
            's_material': ModelSelect2ForwardExtras(url='directory:autocomplete_material', attrs={ 'data-theme': 'bootstrap-5' }),
            }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = _helper()
        self.helper.layout = Layout(
            Div(
                's_material',
                Row(Column('material_count'), Column('material_cost')),
                Row(Column('work_cost'), Column('material_count_fact')),
                Row(Column(Submit('submit', _('Сохранить'), css_class="my-2 px-3"))),
                css_class='my-2 px-4 py-3 border bg-secondary bg-opacity-10'
                )
        )

    def save(self, task, commit=True):
        obj = super().save(commit=False)
        obj.d_task = task

        if (obj.s_material.cost_work != None) and (obj.material_count != None):
            obj.labor_cost = obj.s_material.labor_cost * obj.material_count
        
        if (obj.labor_cost != None) and (obj.work_cost != None):
            obj.work_cost_total = obj.labor_cost * obj.work_cost

        if (obj.material_count != None) and (obj.material_cost != None):
            obj.material_cost_total = obj.material_count * obj.material_cost

        if commit: 
            obj.save()
        return obj
    

class TaskMaterialSubForm(TaskMaterialForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper.layout = Layout(
            Div(
                's_material',
                Row(Column('material_count'), Column('material_cost')),
                Row(Column('work_cost'), Column('material_count_fact')),
                css_class="subform bg-light shadow-sm border p-4 mt-3 mb-4"
            )
        )


class TaskForm(FormsetFormMixin, forms.ModelForm):
    """Форма добавления/редактирования задачи"""
    class Meta:
        model = Task
        fields = [
            'parent',
            's_employee',
            's_work',
            'task_name',
            'date_start',
            'date_stop',
            'date_fact'
            ]
        widgets = {
            'task_name': forms.Textarea(attrs={ 'rows': 2, 'data-height-auto': True }),
            's_employee': ModelSelect2ForwardExtras(
                url='directory:autocomplete_employee', 
                forward=[forward.Const('1', 'is_active')],
                attrs={ 'data-theme': 'bootstrap-5' }),
            's_work': ModelSelect2ForwardExtras(
                url='directory:autocomplete_work', attrs={ 'data-theme': 'bootstrap-5' }),
            'date_start': forms.NumberInput(attrs={ 'type': 'date' }),
            'date_stop': forms.NumberInput(attrs={ 'type': 'date' }),
            'date_fact': forms.NumberInput(attrs={ 'type': 'date' })
            }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        if not self.instance.pk:
            self.fields['parent'] = forms.ModelChoiceField(
                label=_('Родительская запись'),
                queryset=Task.objects.all(),
                widget=ModelSelect2ForwardExtras(url='directory:autocomplete_task', attrs={ 'data-theme': 'bootstrap-5' }),
                required=False
                )
        else:
            self.fields['parent'] = forms.ModelChoiceField(
                label=_('Родительская запись'),
                queryset=Task.objects.all().exclude(pk__in=[o.pk for o in self.instance.get_descendants(include_self=True)]),
                widget=ModelSelect2ForwardExtras(
                    url='directory:autocomplete_task', 
                    forward=[
                        forward.Const(self.instance.pk, 'self'),
                        forward.Const(True, 'exclude_children')
                        ],
                    unselect_if_forward_changed=True,
                    attrs={ 'data-theme': 'bootstrap-5' }
                    ),
                required=False
                )
            

        task_material_list_formset = forms.modelformset_factory(TaskMaterial, 
            form=TaskMaterialSubForm, formset=ModelFormSet, extra=1, can_delete=True)
        
        if self.instance.pk:
            self.fields['task_material_list'] = FormsetField(task_material_list_formset, 
                form_kwargs={ 'empty_permitted': True },
                formset_queryset=self.instance.task_material_list.all())
            
        else:
            self.fields['task_material_list'] = FormsetField(task_material_list_formset,
                form_kwargs={ 'empty_permitted': True },
                formset_queryset=TaskMaterial.objects.none())
            
            
        self.helper = _helper()
        self.helper.layout = Layout(
            Div(
                'parent',
                'task_name',
                Row(
                    Column('date_start', css_class='col-4'),
                    Column('date_stop', css_class='col-4'),
                    Column('date_fact', css_class='col-4'),
                ),
                's_employee',
                's_work',
                Div(
                    HTML('''<h5 class="mb-1">Материалы</h5>'''),
                    'task_material_list',
                    css_class="bg-secondary bg-opacity-10 px-4 pt-3 pb-1 mt-4 mb-4",
                    id="task_material_list-subforms"
                ), 
                Row(Column(Submit('submit', _('Сохранить'), css_class="my-2 px-3"))),
                css_class='my-2 px-4 py-3 border bg-secondary bg-opacity-10'
                )
                
        )

    def save(self, commit=True):
        obj = super().save(commit=False)
        if commit: 
            with transaction.atomic():
                obj.save()
                if obj.s_work:
                    self.fields['task_material_list'].formset.save(task=obj)
                else:
                    obj.task_material_list.all().delete()
        return obj

tasks/views/base.py
from django.http import JsonResponse
from django.shortcuts import render, get_object_or_404
from django.utils.translation import gettext_lazy as _
from django.core.paginator import Paginator
from django.contrib.auth.decorators import login_required

from common.utils import get_count_per_page
from common.decorators import deletion_error_capture
from directory.models import Task
from tasks.forms import TaskForm
from tasks.filters import TaskFilterForm


@login_required
def home(request):
    """Каркас страницы"""
    parent_id = request.GET.get('parent')
    return render(request, 'tasks/home.html', {
        'ff': TaskFilterForm(initial={ 'parent': parent_id }),
        'parent': Task.objects.get(pk=parent_id) if parent_id else None,
        'page_title': _('Задачи')
        })


@login_required
def listing(request):
    """Ajax. Список"""
    ff = TaskFilterForm(request.GET)
    paginator = Paginator(ff.qs, get_count_per_page(request=request))
    return render(request, 'tasks/listing.html', {
        'data': paginator.get_page(request.GET.get('page')),
        'ff': ff,
        'count': ff.qs.count()
        })


@login_required
def add(request):
    """Ajax. Добавление"""
    if request.method == 'POST':
        form = TaskForm(request.POST)
        if form.is_valid():
            form.save()
            return listing(request=request)
        return JsonResponse({ 'success': False, 'errors': form.errors })
    return render(request, 'tasks/add.html', { 
        'form': TaskForm() 
        })


@login_required
def change(request, task_pk):
    """Ajax. Редактирование"""
    task = get_object_or_404(Task, pk=task_pk)
    if request.method == 'POST':
        form = TaskForm(request.POST, instance=task)
        if form.is_valid():
            form.save()
            return listing(request=request)
        return JsonResponse({ 'success': False, 'errors': form.errors })
    return render(request, 'tasks/change.html', {
        'form': TaskForm(instance=task),
        'task': task
        })


@login_required
@deletion_error_capture
def delete_complete(request, task_pk):
    """Ajax. Удаление"""
    task = get_object_or_404(Task, pk=task_pk)
    task.delete()
    return listing(request=request)

tasks/views/task_material.py
from django.http import JsonResponse
from django.shortcuts import render, get_object_or_404
from django.utils.translation import gettext_lazy as _
from django.core.paginator import Paginator
from django.contrib.auth.decorators import login_required
from django.db.models import F, DecimalField
from django.db.models.functions import Coalesce    

from common.utils import get_count_per_page
from common.decorators import deletion_error_capture
from directory.models import Task, TaskMaterial
from tasks.forms import TaskMaterialForm


@login_required
def task_material_listing(request, task_pk):
    """Ajax. Список"""
    task = get_object_or_404(Task, pk=task_pk)
    data = (
        task.task_material_list
        .annotate(
            unit_measure=F('s_material__s_unit_measure__unit_name'),
            m_cost_value=F('s_material__cost_value'),
            cost_value_total=Coalesce(F('material_count'), 0, output_field=DecimalField()) * F('s_material__cost_value'),
            m_cost_work=F('s_material__cost_work'),
            cost_work_total=Coalesce(F('s_material__cost_work'), 0, output_field=DecimalField()) * Coalesce(F('s_material__labor_cost'), 0, output_field=DecimalField())
            )
        .select_related()
        )
    paginator = Paginator(data, get_count_per_page(request=request))
    return render(request, 'tasks/task_material/task_material_listing.html', {
        'data': paginator.get_page(request.GET.get('page')),
        'count': data.count(),
        'task': task
        })


@login_required
def task_material_add(request, task_pk):
    """Ajax. Добавление"""
    task = get_object_or_404(Task, pk=task_pk)
    if request.method == 'POST':
        form = TaskMaterialForm(request.POST)
        if form.is_valid():
            form.save(task=task)
            return task_material_listing(request=request, task_pk=task_pk)
        return JsonResponse({ 'success': False, 'errors': form.errors })
    return render(request, 'tasks/task_material/task_material_add.html', { 
        'form': TaskMaterialForm(),
        'task': task
        })


@login_required
def task_material_change(request, task_material_pk):
    """Ajax. Редактирование"""
    m = get_object_or_404(TaskMaterial, pk=task_material_pk)
    task = m.d_task
    if request.method == 'POST':
        form = TaskMaterialForm(request.POST, instance=m)
        if form.is_valid():
            form.save(task=task)
            return task_material_listing(request=request, task_pk=task.pk)
        return JsonResponse({ 'success': False, 'errors': form.errors })
    return render(request, 'tasks/task_material/task_material_change.html', {
        'form': TaskMaterialForm(instance=m),
        'm': m,
        'task': task
        })


@login_required
@deletion_error_capture
def task_material_delete_complete(request, task_material_pk):
    """Ajax. Удаление"""
    m = get_object_or_404(TaskMaterial, pk=task_material_pk)
    task = m.d_task
    m.delete()
    return task_material_listing(request=request, task_pk=task.pk)

tasks/templates/tasks/task_material/task_material_add.html
<form enctype="multipart/form-data" action="{% url 'tasks:task_material_add' task.pk %}?{% url_qs %}" method="post">
    {% include "_parts/form.html" with form=form %}
</form>

tasks/templates/tasks/task_material/task_material_change.html
<form enctype="multipart/form-data" action="{% url 'tasks:task_material_change' m.pk %}?{% url_qs %}" method="post">
    {% include "_parts/form.html" with form=form %}
</form>

tasks/templates/tasks/task_material/task_material_listing.html
{% load humanize %}
<table class="table table-hover table-fixed-head table-bordered border-secondary mt-2 lh-sm small">
    <thead>
        <tr>
            <th scope="col" rowspan="2" class="align-middle">Наименование</th>
            <th scope="col" rowspan="2" class="align-middle">Ед. измер-я</th>
            <th scope="col" rowspan="2" class="align-middle text-center">Кол-во</th>
            <th scope="col" rowspan="2" class="align-middle text-center">Сделано факт-ки</th>
            
            <th scope="col" colspan="2" class="align-middle text-center">Материалы</th>
            <th scope="col" colspan="2" class="align-middle text-center">Работа</th>
            <th scope="col" colspan="2" class="align-middle text-center">Материалы (себестоимость)</th>
            <th scope="col" colspan="2" class="align-middle text-center">Работа (себестоимость)</th>
            
            <th scope="col" rowspan="2" class="align-middle text-center text-nowrap">
                {% if check_perm.tasks.task_material_add %}
                <a class="modal_link" title="Добавить"
                    data-modal-title="Новый материал к работе" 
                    data-modal-size="modal-lg"
                    data-target="#main_modal_body"
                    data-href="{% url 'tasks:task_material_add' task.pk %}?{% url_qs %}">{{ 'Доб.'|action_icon }}</a>
                {% endif %}
            </th>
        </tr>
        <tr>
            <th scope="col" class="align-middle text-center">Цена за ед</th>
            <th scope="col" class="align-middle text-center">Итого, руб.</th>
            <th scope="col" class="align-middle text-center">Цена за ед.</th>
            <th scope="col" class="align-middle text-center">Итого, руб.</th>
            <th scope="col" class="align-middle text-center">Цена за ед</th>
            <th scope="col" class="align-middle text-center">Итого, руб.</th>
            <th scope="col" class="align-middle text-center">Цена за ед.</th>
            <th scope="col" class="align-middle text-center">Итого, руб.</th>
        </tr>
    </thead>
    <tbody>
        {% for o in data %}
        <tr>
            <td>{{ o.s_material }}</td>
            <td>{{ o.unit_measure }}</td>
            <td class=" text-center">{{ o.material_count|filter_none|intcomma }}</td>
            <td class=" text-center">{{ o.material_count_fact|filter_none|intcomma }}</td>
            <td class=" text-center">{{ o.material_cost|filter_none|intcomma }}</td>
            <td class=" text-center">{{ o.material_cost_total|filter_none|intcomma }}</td>
            <td class=" text-center">{{ o.work_cost|filter_none|intcomma }}</td>
            <td class=" text-center">{{ o.work_cost_total|filter_none|intcomma }}</td>
            <td class=" text-center">{{ o.m_cost_value|filter_none|intcomma }}</td>
            <td class=" text-center">{{ o.cost_value_total|filter_none|floatformat:2|intcomma }}</td>
            <td class=" text-center">{{ o.m_cost_work|filter_none|intcomma }}</td>
            <td class=" text-center">{{ o.cost_work_total|filter_none|floatformat:2|intcomma }}</td>
            <td class="text-nowrap text-center">
                {% if check_perm.tasks.task_material_change %}
                <a class="modal_link me-2" title="Изменить" 
                    data-modal-title="Изменение данных материала к работе" 
                    data-modal-size="modal-lg"
                    data-target="#main_modal_body"
                    data-href="{% url 'tasks:task_material_change' o.pk %}?{% url_qs %}">
                    {{ 'Изменить'|action_icon }}
                </a>
                {% endif %}
                {% if check_perm.tasks.task_material_delete_complete %}
                <a class="text-danger dialog_delete" title="Удалить" 
                    data-target="#main_modal_body" 
                    data-href="{% url 'tasks:task_material_delete_complete' o.pk %}?{% url_qs %}">
                    {{'Удалить'|action_icon }}
                </a>
                {% endif %}
            </td>
        </tr>
        {% endfor %}
    </tbody>
    <tfoot>
        <tr>
            <td colspan="100">
                <div class="form-text">Количество записей: {{ count }}</div>
            </td>
        </tr>
    </tfoot>
</table>
<div class="my-2">
    {% url 'tasks:task_material_listing' task.pk as pager_base_url %}
    {% include '_parts/pager_ajax.html' with objects=data target='#main_modal_body' base_url=pager_base_url %}
</div>