home/urls.py
from django.urls import path
from home import views

app_name = 'home'

urlpatterns = [
	path('', views.home, name="home"),
    
]

users/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from users.views import *


app_name = 'users'


urlpatterns = [
    path('login/', login, name='login'),
    path('logout/', logout, name='logout'),
    path('password/change/', password_change, name='password_change'),
]

users/models.py
from django.utils.translation import gettext_lazy as _
from django.contrib.auth.models import AbstractUser, UserManager as DjangoUserManager
from django.utils.functional import cached_property
from django.db import models

from config.casbin import check_str_perm
from common.utils import has_related_object
from common.mixins import InvalidateCachedPropertiesMixin


class UserManager(DjangoUserManager):
    pass


class User(InvalidateCachedPropertiesMixin, AbstractUser):
    """Пользователь"""
    class Meta:
        managed = True
        db_table = 'user'
        verbose_name = _('Пользователь')
        verbose_name_plural = _('Пользователи')

    objects = UserManager()

    @cached_property
    def is_employee(self):
        return has_related_object(self, 'employee')

    @cached_property
    def is_superuser_or_admin(self):
        if self.is_superuser:
            return True
        if self.is_employee and self.employee.is_admin:
            return True
        return False
    
    @cached_property
    def full_name(self):
        if self.is_employee:
            return self.employee.employee_name
        full_name = self.get_full_name()
        return full_name if full_name else self.username

    def check_perm(self, perm):
        return check_str_perm(self, perm)

users/forms.py
from django.contrib.auth.forms import UserCreationForm as DjangoUserCreationForm
from django.contrib.auth.forms import UserChangeForm as DjangoUserChangeForm, AuthenticationForm, PasswordChangeForm
from django.utils.translation import gettext_lazy as _
from django.contrib.auth import get_user_model
from django import forms

from crispy_forms.helper import FormHelper
from crispy_forms.layout import *
from crispy_forms.bootstrap import *


User = get_user_model()


def _helper():
    helper = FormHelper()
    helper.form_tag = False
    helper.include_media = False
    return helper 


class UserCreationForm(DjangoUserCreationForm):
    class Meta:
        model = User
        fields = DjangoUserCreationForm.Meta.fields


class UserChangeForm(DjangoUserChangeForm):
    class Meta:
        model = User
        fields = DjangoUserCreationForm.Meta.fields


class LoginForm(AuthenticationForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['username'].widget = forms.TextInput(
            attrs={ 'placeholder': _('Имя пользователя'), 'class': 'form-control form-control-lg' })
        self.fields['password'].widget = forms.PasswordInput(
            attrs={ 'placeholder': _('Пароль'), 'class': 'form-control form-control-lg' })

        self.helper = _helper()
        self.helper.form_show_labels = False
        self.helper.layout = Layout(
            Div('username', css_class="mt-5 pt-1"),
            Div('password', css_class="mt-5 py-1"),
            Div(Submit('submit', _('Войти'), css_class="w-100 btn-darkprimary btn-lg fs-5"), css_class="mt-4"),
            )


class PassChangeForm(PasswordChangeForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = _helper()
        self.helper.layout = Layout(
            Div(
                'old_password',
                'new_password1',
                'new_password2',
                Row(Column(Submit('submit', _('Сохранить'), css_class="my-2 px-3"))),
                css_class='my-2 px-4 py-3 border bg-secondary bg-opacity-10'
                )
            )
        

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse
from django.utils.translation import gettext_lazy as _
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth import login as auth_login, logout as auth_logout
from django.conf import settings

from users.forms import *


def login(request):
    if request.method == 'POST':
        form = LoginForm(data=request.POST)
        if form.is_valid():
            auth_login(request, form.get_user())
            return JsonResponse({ 'redirect_url': settings.LOGIN_REDIRECT_URL })
        return JsonResponse({ 'success': False, 'errors': form.errors })
    return render(request, 'users/login.html', { 'form': LoginForm() })


@login_required
def logout(request):
    auth_logout(request)
    return redirect(settings.LOGOUT_REDIRECT_URL)


@login_required
def password_change(request):
    """Ajax. Смена пароля текущего пользователя"""
    if request.method == 'POST':
        form = PassChangeForm(data=request.POST, user=request.user)
        if form.is_valid():
            form.save()
            update_session_auth_hash(request, form.user)
            return JsonResponse({ 'success': True, 'message': _('Новый пароль успешно установлен') })
        return JsonResponse({ 'success': False, 'errors': form.errors })
    return render(request, 'users/password_change.html', { 'form': PassChangeForm(user=request.user) })

users/templates/users/login.html
{% load compress %}
<!doctype html>
<html lang="ru">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  {% compress css %}
    <link rel="stylesheet" href="{{ STATIC_URL}}bootstrap/bootstrap.min.css">
    <link rel="stylesheet" href="{{ STATIC_URL }}bootstrap-icons/bootstrap-icons.min.css" />
    <link rel="stylesheet" href="{{ STATIC_URL}}css/app.css">
    <link rel="stylesheet" href="{{ STATIC_URL}}css/styles.css">
    <style>
      @font-face {
          font-family: HelveticaNeue;
          font-weight: 100;
          src: url("/static/fonts/HelveticaNeue-Thin.otf") format("opentype");
      }
      @font-face {
          font-family: HelveticaNeue;
          font-weight: normal;
          src: url("/static/fonts/HelveticaNeue-Roman.otf") format("opentype");
      }
      .password-control {
          position: absolute;
          top: 12px;
          right: 10px;
          display: inline-block;
          width: 20px;
          height: 20px;
          color: #888 !important;
      }
    </style>
  {% endcompress %}
  <title>ХАКАТОН</title>
</head>

<body style='
    font-family: HelveticaNeue, sans-serif; 
    background-image: linear-gradient(#24357B, #08195B)'>

    <div class="vh-100" style="
        background-repeat: no-repeat;
        background-position: center bottom;
        background-size: 100% 30%;">

        <div class="container vh-100 d-flex flex-column justify-content-between p-5" style="width:80%;">

            

            <div class="d-flex align-items-center flex-grow-1">
                <div class="row w-100 mt-lg-4">

                    <div class="col-12 col-lg mt-5 mt-lg-0">
                        <div class="display-3 opacity-75 text-white lh-1 fw-light text-center text-lg-start">
                            Работа найдётся<br>
                            для каждого
                        </div>
                        <div class="opacity-50 text-white mt-4 fs-5 fw-light text-center text-lg-start">
                            Постоянный количественный рост и сфера нашей<br>
                            активности является качественно новой ступенью<br>
                            как самодостаточных.
                        </div>
                    </div>
    
                    <div class="col-12 col-lg-auto mt-5 mt-lg-0 d-flex justify-content-center justify-content-lg-end">
                        <div class="card bg-white rounded-2 border-0 shadow shadow-lg" style="width:28rem;">
                            <div class="card-body p-5">
                                <div class="fw-bold fs-3 text-center lh-1 mb-5" style="color: #24357D;">Войдите в систему</div>
                                <form class="ajax-form" enctype="multipart/form-data" action="{% url 'users:login' %}" method="post">
                                    {% include "_parts/form.html" with form=form %}
                                </form>
                            </div>
                        </div>
                    </div>
    
                </div>
            </div>

        </div>


    </div>
    
</body>
{% compress js %}
<script src="{{ STATIC_URL}}jquery/jquery-3.6.0.min.js"></script>
<script src="{{ STATIC_URL }}bootstrap/bootstrap.bundle.min.js"></script>
<script src="{{ STATIC_URL }}js/app.js"></script>
{% endcompress %}
</html>

users/templates/users/password_change.html
<form enctype="multipart/form-data" action="{% url 'users:password_change' %}" method="post">
    {% include "_parts/form.html" with form=form %}
</form>